kind: ConfigMap
apiVersion: v1
metadata:
  name: basket-cm
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: basket
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://0.0.0.0:80
  IdentityUrl: http://identity-api
  IdentityUrlExternal: {{.Values.protcol }}://{{ .Values.identityUrlExternal }}
  SeqServerUrl: {{ .Values.protcol }}://{{ .Values.seqFqdn }}

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: basket
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: basket
spec:
  replicas: 1
  selector:
    matchLabels:
      service: basket
  template:
    metadata:
      labels:
        app: eshop
        service: basket
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "basket-api"
        dapr.io/app-port: "80"
        dapr.io/config: "dapr-config"
        dapr.io/log-as-json: "true"
    spec:
      containers:
        - name: basket-api
          image: eshopdapr/basket.api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: basket-cm
          readinessProbe:
            httpGet:
              path: /hc
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: basket-api
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: basket
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    service: basket
